---
pool: "ubuntu-22.04"

trigger: 
  - main

stages:   
  - stage: 'BuildandIntegration'
    displayName: CIpetclinic
    jobs:
      - job: mavenjob
        displayName: maven
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              jdkVersionOption: '1.17'
           